### ISSUE TITLE
Check if the page is already in cache before rendering

### ISSUE THREAD

**Issue by frederikhors** [turbolinks/turbolinks#488]
I'm using the code below to add and remove css classes on my `container div`.

**javascript**:
```js
Turbolinks.start()

document.addEventListener('turbolinks:render', function () {
  if (document.documentElement.hasAttribute('data-turbolinks-preview')) {
    document.querySelector('container').classList.add('animated', 'fadeIn')
  } else {
    document.querySelector('container').classList.remove('animated', 'fadeIn')
  }
})
```

**css**:
```css
.animated {
  animation-duration: 1s;
  animation-fill-mode: both;
}

.fadeIn {
  animation-name: fadeIn;
}

@keyframes fadeIn {
  from { opacity: 0 }
  to { opacity: 1 }
}
```

It works great when I navigate my site but there is a problem.

**ACTUAL STATE**:

When the first time Turbolinks loads the page it doesn't fade.
The same page loaded from second time works great.

**EXPECTED STATE**:

I need a way to check if the next page is already in cache or not.

**Is there a way?**
